
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 15 00:48:59 ART 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CTdsSymbol {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int L_PAREN = 37;
  public static final int CONTINUE = 11;
  public static final int R_PAREN = 38;
  public static final int INT = 3;
  public static final int LESS = 21;
  public static final int FOR = 8;
  public static final int MINUS = 17;
  public static final int NOT = 29;
  public static final int AND = 31;
  public static final int uNOT = 39;
  public static final int OR = 32;
  public static final int COMMA = 41;
  public static final int CLASS = 2;
  public static final int EXTERN = 12;
  public static final int PLUS = 16;
  public static final int IF = 6;
  public static final int ID = 47;
  public static final int DOT = 40;
  public static final int R_BRACKET = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 13;
  public static final int GTR = 22;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int SEMI_COLON = 42;
  public static final int MOD = 20;
  public static final int BREAK = 10;
  public static final int VOID = 14;
  public static final int EQ = 23;
  public static final int TIMES = 18;
  public static final int L_BRACE = 33;
  public static final int ELSE = 7;
  public static final int R_BRACE = 34;
  public static final int NOT_EQ = 30;
  public static final int WHILE = 9;
  public static final int LESS_EQ = 26;
  public static final int FLOAT = 4;
  public static final int PLUS_EQ = 24;
  public static final int MINUS_EQ = 25;
  public static final int FALSE = 46;
  public static final int FLOAT_LITERAL = 44;
  public static final int L_BRACKET = 35;
  public static final int GTR_EQ = 27;
  public static final int PRINT = 15;
  public static final int INT_LITERAL = 43;
  public static final int EQ_EQ = 28;
}

