
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 02 02:08:42 ART 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int float_literal = 3;
  public static final int int_literal = 2;
  public static final int EOF = 0;
}

